# Generated by Django 4.1.3 on 2022-12-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name',
        ),
    ]
